[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "MrtNanxhE1h81B3cPfBsGsfpL2uc7de5vpQ5uREWrrR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
